---
all:
  ## ALL HOSTS THAT EXIST   
  hosts:                           # IP ADDRESSES        # DESCRIPTION   
    node1:
      ansible_host:               34.65.251.233
    node2:
      ansible_host:               34.65.94.180
    node3:
      ansible_host:               34.65.12.216
    node4:
      ansible_host:               34.65.185.100

  ## GROUPS
  children:
    consul_cluster:
      hosts:
        node1:
        node2:
        node3:
        node4:
    consul_serverss:
      hosts:
        node1:
    consul_nodes:
      hosts:
        node2:
        node3:
        node4: